version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  flight-service:
    build: ./flight-service
    container_name: flight-service
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8060
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: flights
    ports:
      - "8060:8060"

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8070
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: tickets
    ports:
      - "8070:8070"

  bonus-service:
    build: ./bonus-service
    container_name: bonus-service
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8050
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: privileges
    ports:
      - "8050:8050"

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: on-failure
    depends_on:
      - flight-service
      - ticket-service
      - bonus-service
    environment:
      PORT: 8080
      FLIGHT_SERVICE_URL: http://flight-service:8060
      TICKET_SERVICE_URL: http://ticket-service:8070
      BONUS_SERVICE_URL: http://bonus-service:8050
      CB_FAILURE_THRESHOLD: 3
      CB_RESET_TIMEOUT_MS: 1000
      CB_REQUEST_TIMEOUT_MS: 3000
      RETRY_INTERVAL_MS: 2000
    ports:
      - "8080:8080"

volumes:
  db-data:
